Development cpu grid2
threefoldtech/tfgrid_stats pull request #41
Opened 2022-08-17 10:00 UTC by maayarosama

### Description
Added CPU numbers from grid2.

### Related Issues

#38

2022-08-17 10:40 UTC, zaelgohary requested changes
make sure to remove the online RAM suffix from cardDetails as well or else toTeraOrGiga filter won't work.

2022-08-27 14:00 UTC, AhmedHanafy725 requested changes

2022-08-27 14:00 UTC, AhmedHanafy725 commented on src/components/CardList.svelte
> +        data: data.totalCru + 14438,
can we re-check grid2 values? I see half of this number on the grid2 explorer

2022-08-28 14:01 UTC, AhmedHanafy725 approved these changes

2022-08-28 14:03 UTC, zaelgohary approved these changes

2022-08-28 14:03 UTC, merged