Fixing conversion rate
threefoldtech/tfgrid_stats pull request #42
Opened 2022-08-25 15:08 UTC by zaelgohary

fixing conversion rate for stats cards.

related issues: 
- https://github.com/threefoldtech/tfgrid_stats/issues/37

2022-08-27 13:58 UTC, AhmedHanafy725 requested changes

2022-08-27 13:58 UTC, AhmedHanafy725 commented on src/filters/toTeraOrGiga.ts
> +  gb = gb / 1024;
can we use better names for variables?

2022-08-28 09:49 UTC, zaelgohary commented on src/filters/toTeraOrGiga.ts
> +  gb = gb / 1024;
done.

2022-08-28 14:00 UTC, AhmedHanafy725 approved these changes

2022-08-28 14:00 UTC, merged