Adding repo docs
threefoldtech/tfgrid_stats pull request #59
Opened 2023-01-05 11:10 UTC by zaelgohary

### Description

Docs added

### Related Issues

- https://github.com/threefoldtech/tfgrid_stats/issues/58

### Checklist

- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings

2023-01-05 11:51 UTC, maayarosama commented on README.md
> +Grid Stats is an application created to replace explorer.threefold.io with a simple page showing a capacity map + statistics.
is a web application

2023-01-05 11:52 UTC, maayarosama commented on README.md
> +
mention what the the capacity map and statistics exactly show

2023-01-05 11:54 UTC, maayarosama commented on docs/release.md
> +In [charts.yaml](../tfgrid-stats/Chart.yaml) replace the value of `appVersion` with the new release tag.
and we should replace the tag value in values.yaml

2023-01-05 11:55 UTC, maayarosama commented on docs/release.md
> +  Create a new issue of type `Update Request` and mention the following:
mention creating a new tag while creating a new release

2023-01-05 12:00 UTC, maayarosama commented
Open an issue for the lack of tests and code coverage

2023-01-05 12:02 UTC, maayarosama commented
Add a small section giving a brief explanation for each available workflow

2023-01-05 12:39 UTC, zaelgohary commented on README.md
> +Grid Stats is an application created to replace explorer.threefold.io with a simple page showing a capacity map + statistics.
done.

2023-01-05 12:39 UTC, zaelgohary commented on README.md
> +
done.

2023-01-05 12:41 UTC, zaelgohary commented on docs/release.md
> +In [charts.yaml](../tfgrid-stats/Chart.yaml) replace the value of `appVersion` with the new release tag.
done.

2023-01-05 12:42 UTC, zaelgohary commented on docs/release.md
> +  Create a new issue of type `Update Request` and mention the following:
done.

2023-01-09 11:06 UTC, maayarosama commented on README.md
> +Grid Stats is a web application created to replace explorer.threefold.io with a simple page showing a capacity map + statistics. In the map, you get to see node distripution with each node location h
node distribution

2023-01-09 11:09 UTC, maayarosama commented on docs/release.md
> +In [charts.yaml](../tfgrid-stats/Chart.yaml) replace the value of `appVersion` with the new release tag. Then, in [values.yaml](../tfgrid-stats/values.yaml) change the tag version with the new releas
Separate the charts.yaml part and the values.yaml part and add ```tag:x.x.x``` as you did with the appVersion

2023-01-09 11:12 UTC, maayarosama commented on docs/release.md
> +  Create a new release with the new tag added in `appVersion` & `Charts.yaml`.
Mention the steps with little description

2023-01-09 11:13 UTC, maayarosama commented on docs/release.md
> +  ![image](https://user-images.githubusercontent.com/62248851/210758782-1ff46374-9e4b-4e0d-a318-a7bf114022b1.png)
change this screenshot to one updating tfgrid_stats rather than grid_weblets

2023-01-09 11:15 UTC, maayarosama commented on docs/workflows.md
> +# Weblets workflows
Tfgrid_stats

2023-01-09 11:38 UTC, zaelgohary commented on docs/release.md
> +  Create a new release with the new tag added in `appVersion` & `Charts.yaml`.
All steps needed are provided in the link in the exact step.

2023-01-10 09:36 UTC, maayarosama commented on README.md
> +
add 
``` cd tfgrid_stats```

2023-01-10 10:12 UTC, maayarosama commented
LGTM, @xmonader please check.

2023-01-10 11:08 UTC, 0oM4R requested changes

2023-01-10 11:08 UTC, 0oM4R commented on docs/release.md
> +
maybe we need to add tags type, as in weblets
```suggestion

> NOTE: We use prereleases for Qanet and Testnet and releases for Mainnet.
### Tags type based on network:
| tag  | network | e.g
|-----|---------| ---------
|   --   | mainnet | 1.0.0
| qa   | qanet   | 1.0.0-qa1
| rc   | testnet | 1.0.0-rc1


```

2023-01-10 11:08 UTC, 0oM4R commented on README.md
>  ```
add how to serve it

2023-01-10 11:15 UTC, zaelgohary commented on docs/release.md
> +
No need to add tags for prereleases as the repo doesn't contain QA or Testnet.

2023-01-10 11:19 UTC, zaelgohary commented on README.md
>  ```
done.

2023-01-10 11:20 UTC, maayarosama approved these changes

2023-01-10 11:24 UTC, 0oM4R approved these changes

2023-01-10 11:25 UTC, merged